title: 量子コンピューティング・ワークブック
author: 東京大学素粒子物理国際研究センター
logo: figs/icepp.jpg

execute:
  execute_notebooks: auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  
only_build_toc_files: true

parse:
  myst_enable_extensions:
    - dollarmath
    - smartquotes

latex:
  latex_documents:
    targetname: qc-workbook_ja.tex

html:
  favicon: figs/favicon_icepp.png
  use_repository_button: true
  use_edit_page_button: true

repository:
  url: "https://github.com/UTokyo-ICEPP/qc-workbook"
  path_to_book: source/ja
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true

sphinx:
  config:
    myst_footnote_transition: false

#bibtex_bibfiles:
#  - references.bib