name: publish

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest
      uses: actions/checkout@v2

    - name: Build the books
      run: |
        docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/qc-workbook yiiyama/jupyterbook-qiskit:1.0.11 /qc-workbook/build-runner/build_and_publish.py --account $GITHUB_REPOSITORY_OWNER --keep-reports

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/ja/_build/html
