name: publish

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest
      uses: actions/checkout@v2

    - name: Build the books
      run: |
        docker run --name buildenv --mount type=bind,src=$GITHUB_WORKSPACE,dst=/tmp/qc-workbook yiiyama/jupyterbook-qiskit:1.0.6 /tmp/qc-workbook/build-runner/build_and_publish.py
        docker exec buildenv /tmp/qc-workbook/build-runner/build_and_publish.py --lang en --target /tmp/qc-workbook/build-en
        docker exec buildenv mkdir /tmp/qc-workbook/build/_build/html/en
        docker exec buildenv cp -r /tmp/qc-workbook/build-en/_build/html/* /tmp/qc-workbook/build/_build/html/en/
        docker stop buildenv
        docker container rm buildenv

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/_build/html
